name: lakehouse_platform
version: 1.0.0
profile: lakehouse_platform

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  lakehouse_platform:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts

vars:
  start_date: "2026-01-01"

seeds:
  lakehouse_platform:
    events:
      +schema: bronze
      +column_types:
        id: varchar
        event_type: varchar
        event_timestamp: timestamp
        user_id: varchar
        payload: varchar
